# Generated by Django 5.0.3 on 2024-04-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Medical Observation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nutritionist_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Nutritionist Observation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_trainer_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Personal Trainer Observation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='psychologist_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Psychologist Observation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_id', models.IntegerField(verbose_name='Professional ID')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profession')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Time')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_id', models.IntegerField(verbose_name='Professional ID')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profession')),
                ('object_tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Object Tag')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
    ]
